<a href="https://colab.research.google.com/github/Juan-Vega18/-ANALISIS-EXPLOR-DE-DATOS---63510/blob/main/clase_data_frame_merging.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [6]:
movies = pd.read_csv('https://raw.githubusercontent.com/Gustavo-Bruges/movies/refs/heads/main/movies.csv')
ratings = pd.read_csv('https://raw.githubusercontent.com/Gustavo-Bruges/movies/refs/heads/main/ratings.csv')

In [17]:
print(f'El head de movies es: \n\n{movies.head(30)}')
print('*'*60)
print(f'El info de movies es: \n\n{movies.info}')
print('*'*60)
print(f'El shape de movies es: \n\n{movies.shape}')

El head de movies es:

    Unnamed: 0      id                                              title  \
0            0     257                                       Oliver Twist
1            1   14290                               Better Luck Tomorrow
2            2   38365                                          Grown Ups
3            3    9672                                           Infamous
4            4   12819                                    Alpha and Omega
5            5   49529                                        John Carter
6            6   75638                                         Red Lights
7            7   13785                                       Best in Show
8            8   20024                              The End of the Affair
9            9   18841                       The Lost Skeleton of Cadavra
10          10   76757                                  Jupiter Ascending
11          11  158752                               Escape from Tomorrow
12          12   10956                                           Joe Dirt
13          13    2757                                        Adaptation.
14          14  308531   Teenage Mutant Ninja Turtles: Out of the Shadows
15          15   16186                         Diary of a Mad Black Woman
16          16    2610                                           Shopgirl
17          17   13074                             Resurrecting the Champ
18          18   26672                          The Thief and the Cobbler
19          19   21334                                 Children of Heaven
20          20   15301                           Twilight Zone: The Movie
21          21      59                              A History of Violence
22          22   10586                         The Ghost and the Darkness
23          23   55180                                 The Last Big Thing
24          24  157058  30 Nights of Paranormal Activity With the Devi...
25          25   24100                                 The Little Vampire
26          26    9793                              The Hills Have Eyes 2
27          27   10735                                  What a Girl Wants
28          28    9353                                        Nacho Libre
29          29    8452                                        The 6th Day

    popularity release_date
0    20.415572   2005-09-23
1     3.877036   2002-01-12
2    38.864027   2010-06-24
3     3.680896   2006-11-16
4    12.300789   2010-09-17
5    43.926995   2012-03-07
6    22.748174   2012-03-02
7    10.982255   2000-09-19
8     6.921263   1999-12-03
9     1.680525   2001-09-12
10   85.369080   2015-02-04
11    1.352222   2013-10-11
12   15.976335   2001-04-10
13   26.441669   2002-12-06
14   39.873791   2016-06-01
15    3.784535   2005-02-25
16    4.820166   2005-10-21
17    4.898437   2007-06-14
18    2.439184   1993-09-23
19    7.072118   1997-08-01
20   12.902975   1983-06-24
21   34.628738   2005-09-23
22   12.465250   1996-10-11
23    0.678475   1998-09-23
24    1.737032   2013-01-14
25    4.365196   2000-10-27
26   17.141376   2007-03-22
27    7.057765   2003-03-27
28   14.642055   2006-06-16
29   18.447479   2000-11-17
************************************************************
El info de movies es:

<bound method DataFrame.info of       Unnamed: 0     id                 title  popularity release_date
0              0    257          Oliver Twist   20.415572   2005-09-23
1              1  14290  Better Luck Tomorrow    3.877036   2002-01-12
2              2  38365             Grown Ups   38.864027   2010-06-24
3              3   9672              Infamous    3.680896   2006-11-16
4              4  12819       Alpha and Omega   12.300789   2010-09-17
...          ...    ...                   ...         ...          ...
4798        4798   3089             Red River    5.344815   1948-08-26
4799        4799  11934   The Hudsucker Proxy   14.188982   1994-03-11
4800        4800  13807                Exiled    8.486390   2006-09-06
4801        4801  73873          Albert Nobbs    7.802245   2011-12-21
4802        4802  11622   Blast from the Past    8.737058   1999-02-12

[4803 rows x 5 columns]>
************************************************************
El shape de movies es:

(4803, 5)

In [18]:
print(f'El head de ratings es: \n\n{ratings.head(30)}')
print('*'*60)
print(f'El info de ratings es: \n\n{ratings.info}')
print('*'*60)
print(f'El shape de ratings es: \n\n{ratings.shape}')

El head de ratings es:

    Unnamed: 0      id  vote_average  vote_count
0            0   19995           7.2     11800.0
1            1     285           6.9      4500.0
2            2  206647           6.3      4466.0
3            3   49026           7.6      9106.0
4            4   49529           6.1      2124.0
5            5     559           5.9      3576.0
6            6   38757           7.4      3330.0
7            7   99861           7.3      6767.0
8            8     767           7.4      5293.0
9            9  209112           5.7      7004.0
10          10    1452           5.4      1400.0
11          11   10764           6.1      2965.0
12          12      58           7.0      5246.0
13          13   57201           5.9      2311.0
14          14   49521           6.5      6359.0
15          15    2454           6.3      1630.0
16          16   24428           7.4     11776.0
17          17    1865           6.4      4948.0
18          18   41154           6.2      4160.0
19          19  122917           7.1      4760.0
20          20    1930           6.5      6586.0
21          21   20662           6.2      1398.0
22          22   57158           7.6      4524.0
23          23    2268           5.8      1303.0
24          24     254           6.6      2337.0
25          25     597           7.5      7562.0
26          26  271110           7.1      7241.0
27          27   44833           5.5      2114.0
28          28  135397           6.5      8662.0
29          29   37724           6.9      7604.0
************************************************************
El info de ratings es:

<bound method DataFrame.info of       Unnamed: 0      id  vote_average  vote_count
0              0   19995           7.2     11800.0
1              1     285           6.9      4500.0
2              2  206647           6.3      4466.0
3              3   49026           7.6      9106.0
4              4   49529           6.1      2124.0
...          ...     ...           ...         ...
4798        4798    9367           6.6       238.0
4799        4799   72766           5.9         5.0
4800        4800  231617           7.0         6.0
4801        4801  126186           5.7         7.0
4802        4802   25975           6.3        16.0

[4803 rows x 4 columns]>
************************************************************
El shape de ratings es:

(4803, 4)

La metodologia consiste en:

`df1.merge(df2, aqui hay que darle la columna con la cual vamos a unir, esperamos que se llamen igual)`

por ejemplo, en nuestro caso puede ser `id`
`df1.merge(df2, on='id')`

In [21]:
#Unir los dataframes
movie_ratings = movies.merge(ratings, on='id')
movie_ratings.drop(['Unnamed: 0_x','Unnamed: 0_y'], axis=1, inplace=True)
movie_ratings.head()

#axis = 1 significa columnas
#inplace = True, modifica el dataframe original y lo reemplaza.

,id,title,popularity,release_date,vote_average,vote_count
0,257,Oliver Twist,20.415572,2005-09-23,6.7,274.0
1,14290,Better Luck Tomorrow,3.877036,2002-01-12,6.5,27.0
2,38365,Grown Ups,38.864027,2010-06-24,6.0,1705.0
3,9672,Infamous,3.680896,2006-11-16,6.4,60.0
4,12819,Alpha and Omega,12.300789,2010-09-17,5.3,124.0

In [23]:
movie_genders = pd.read_csv('https://raw.githubusercontent.com/Gustavo-Bruges/movies/refs/heads/main/movie_to_genres.csv')
movie_genders

       Unnamed: 0  movie_id            genre
0               0         5            Crime
1               1         5           Comedy
2               2        11  Science Fiction
3               3        11           Action
4               4        11        Adventure
...           ...       ...              ...
12155       12155    426469            Drama
12156       12156    433715         Thriller
12157       12157    433715            Drama
12158       12158    447027           Family
12159       12159    459488      Documentary

[12160 rows x 3 columns]

In [24]:
movie_genders.drop(['Unnamed: 0'], axis=1, inplace=True)

In [25]:
movie_genders

       movie_id            genre
0             5            Crime
1             5           Comedy
2            11  Science Fiction
3            11           Action
4            11        Adventure
...         ...              ...
12155    426469            Drama
12156    433715         Thriller
12157    433715            Drama
12158    447027           Family
12159    459488      Documentary

[12160 rows x 2 columns]

In [26]:
movies_with_genders = movies.merge(movie_genders, left_on='id', right_on='movie_id')
#left on es el dataset fuera de merge
#el right on es el dataset dentro de merge.

In [30]:
movies_with_genders

          id                 title  popularity release_date  movie_id    genre
0        257          Oliver Twist   20.415572   2005-09-23       257    Crime
1        257          Oliver Twist   20.415572   2005-09-23       257    Drama
2        257          Oliver Twist   20.415572   2005-09-23       257   Family
3      14290  Better Luck Tomorrow    3.877036   2002-01-12     14290    Crime
4      14290  Better Luck Tomorrow    3.877036   2002-01-12     14290    Drama
...      ...                   ...         ...          ...       ...      ...
12155  13807                Exiled    8.486390   2006-09-06     13807    Crime
12156  13807                Exiled    8.486390   2006-09-06     13807   Action
12157  73873          Albert Nobbs    7.802245   2011-12-21     73873    Drama
12158  11622   Blast from the Past    8.737058   1999-02-12     11622   Comedy
12159  11622   Blast from the Past    8.737058   1999-02-12     11622  Romance

[12160 rows x 6 columns]

In [54]:
movies_with_genders_copy = movies_with_genders.copy()
print(movies_with_genders_copy['popularity'].sort_values())
print(movies_with_genders_copy.iloc[2107])

2107       0.000372
2105       0.000372
2106       0.000372
2108       0.000372
4288       0.001117
            ...
10954    724.247784
11503    875.581305
11505    875.581305
11502    875.581305
11504    875.581305
Name: popularity, Length: 12160, dtype: float64
id                        77156
title                Alien Zone
popularity             0.000372
release_date         1978-11-22
movie_id                  77156
genre           Science Fiction
Name: 2107, dtype: object

In [74]:
sci_movies = movies_with_genders[movies_with_genders['genre'] == 'Science Fiction']
sci_movies
#sci_movies.shape

,id,title,popularity,release_date,movie_id,genre
9,49529,John Carter,43.926995,2012-03-07,49529,Science Fiction
17,18841,The Lost Skeleton of Cadavra,1.680525,2001-09-12,18841,Science Fiction
21,76757,Jupiter Ascending,85.369080,2015-02-04,76757,Science Fiction
46,26672,The Thief and the Cobbler,2.439184,1993-09-23,26672,Science Fiction
53,15301,Twilight Zone: The Movie,12.902975,1983-06-24,15301,Science Fiction
...,...,...,...,...,...,...
12032,5491,Battlefield Earth,7.891470,2000-05-10,5491,Science Fiction
12044,1576,Resident Evil,40.715623,2002-03-15,1576,Science Fiction
12052,13006,Split Second,4.857028,1992-05-01,13006,Science Fiction
12132,11058,Godsend,12.102350,2004-04-30,11058,Science Fiction
12146,869,Planet of the Apes,51.188633,2001-07-25,869,Science Fiction

In [77]:
action_movies = movies_with_genders[movies_with_genders['genre'] == 'Action']
action_movies

,id,title,popularity,release_date,movie_id,genre
11,49529,John Carter,43.926995,2012-03-07,49529,Action
20,76757,Jupiter Ascending,85.369080,2015-02-04,76757,Action
34,308531,Teenage Mutant Ninja Turtles: Out of the Shadows,39.873791,2016-06-01,308531,Action
71,19995,Avatar,150.437577,2009-12-10,19995,Action
79,27205,Inception,167.583710,2010-07-14,27205,Action
...,...,...,...,...,...,...
12099,34723,The Adventures of Huck Finn,2.163683,1993-04-02,34723,Action
12126,792,Platoon,49.802914,1986-12-18,792,Action
12140,116613,The Sweeney,6.938854,2012-09-11,116613,Action
12148,869,Planet of the Apes,51.188633,2001-07-25,869,Action
12156,13807,Exiled,8.486390,2006-09-06,13807,Action

In [83]:
df_left = action_movies.merge(sci_movies, on='movie_id', how ='left')

In [84]:
df_left

,id_x,title_x,popularity_x,release_date_x,movie_id,genre_x,id_y,title_y,popularity_y,release_date_y,genre_y
0,49529,John Carter,43.926995,2012-03-07,49529,Action,49529.0,John Carter,43.926995,2012-03-07,Science Fiction
1,76757,Jupiter Ascending,85.369080,2015-02-04,76757,Action,76757.0,Jupiter Ascending,85.369080,2015-02-04,Science Fiction
2,308531,Teenage Mutant Ninja Turtles: Out of the Shadows,39.873791,2016-06-01,308531,Action,NaN,NaN,NaN,NaN,NaN
3,19995,Avatar,150.437577,2009-12-10,19995,Action,19995.0,Avatar,150.437577,2009-12-10,Science Fiction
4,27205,Inception,167.583710,2010-07-14,27205,Action,27205.0,Inception,167.583710,2010-07-14,Science Fiction
...,...,...,...,...,...,...,...,...,...,...,...
1149,34723,The Adventures of Huck Finn,2.163683,1993-04-02,34723,Action,NaN,NaN,NaN,NaN,NaN
1150,792,Platoon,49.802914,1986-12-18,792,Action,NaN,NaN,NaN,NaN,NaN
1151,116613,The Sweeney,6.938854,2012-09-11,116613,Action,NaN,NaN,NaN,NaN,NaN
1152,869,Planet of the Apes,51.188633,2001-07-25,869,Action,869.0,Planet of the Apes,51.188633,2001-07-25,Science Fiction
1153,13807,Exiled,8.486390,2006-09-06,13807,Action,NaN,NaN,NaN,NaN,NaN

In [85]:
df_left_suf = action_movies.merge(sci_movies, on='movie_id', how ='left', suffixes=("_action","_scifi"))

In [86]:
df_left_suf

,id_action,title_action,popularity_action,release_date_action,movie_id,genre_action,id_scifi,title_scifi,popularity_scifi,release_date_scifi,genre_scifi
0,49529,John Carter,43.926995,2012-03-07,49529,Action,49529.0,John Carter,43.926995,2012-03-07,Science Fiction
1,76757,Jupiter Ascending,85.369080,2015-02-04,76757,Action,76757.0,Jupiter Ascending,85.369080,2015-02-04,Science Fiction
2,308531,Teenage Mutant Ninja Turtles: Out of the Shadows,39.873791,2016-06-01,308531,Action,NaN,NaN,NaN,NaN,NaN
3,19995,Avatar,150.437577,2009-12-10,19995,Action,19995.0,Avatar,150.437577,2009-12-10,Science Fiction
4,27205,Inception,167.583710,2010-07-14,27205,Action,27205.0,Inception,167.583710,2010-07-14,Science Fiction
...,...,...,...,...,...,...,...,...,...,...,...
1149,34723,The Adventures of Huck Finn,2.163683,1993-04-02,34723,Action,NaN,NaN,NaN,NaN,NaN
1150,792,Platoon,49.802914,1986-12-18,792,Action,NaN,NaN,NaN,NaN,NaN
1151,116613,The Sweeney,6.938854,2012-09-11,116613,Action,NaN,NaN,NaN,NaN,NaN
1152,869,Planet of the Apes,51.188633,2001-07-25,869,Action,869.0,Planet of the Apes,51.188633,2001-07-25,Science Fiction
1153,13807,Exiled,8.486390,2006-09-06,13807,Action,NaN,NaN,NaN,NaN,NaN

In [87]:
#Ahora una union derecha
df_r_suf = action_movies.merge(sci_movies, on='movie_id', how ='right', suffixes=("_action","_scifi"))

In [88]:
df_r_suf

,id_action,title_action,popularity_action,release_date_action,movie_id,genre_action,id_scifi,title_scifi,popularity_scifi,release_date_scifi,genre_scifi
0,49529.0,John Carter,43.926995,2012-03-07,49529,Action,49529,John Carter,43.926995,2012-03-07,Science Fiction
1,NaN,NaN,NaN,NaN,18841,NaN,18841,The Lost Skeleton of Cadavra,1.680525,2001-09-12,Science Fiction
2,76757.0,Jupiter Ascending,85.369080,2015-02-04,76757,Action,76757,Jupiter Ascending,85.369080,2015-02-04,Science Fiction
3,NaN,NaN,NaN,NaN,26672,NaN,26672,The Thief and the Cobbler,2.439184,1993-09-23,Science Fiction
4,NaN,NaN,NaN,NaN,15301,NaN,15301,Twilight Zone: The Movie,12.902975,1983-06-24,Science Fiction
...,...,...,...,...,...,...,...,...,...,...,...
530,5491.0,Battlefield Earth,7.891470,2000-05-10,5491,Action,5491,Battlefield Earth,7.891470,2000-05-10,Science Fiction
531,1576.0,Resident Evil,40.715623,2002-03-15,1576,Action,1576,Resident Evil,40.715623,2002-03-15,Science Fiction
532,13006.0,Split Second,4.857028,1992-05-01,13006,Action,13006,Split Second,4.857028,1992-05-01,Science Fiction
533,NaN,NaN,NaN,NaN,11058,NaN,11058,Godsend,12.102350,2004-04-30,Science Fiction
534,869.0,Planet of the Apes,51.188633,2001-07-25,869,Action,869,Planet of the Apes,51.188633,2001-07-25,Science Fiction