<a href="https://colab.research.google.com/github/Juan-Vega18/-ANALISIS-EXPLOR-DE-DATOS---63510/blob/main/Limpieza_De_datos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from google.colab import drive
drive.mount('/mnt/drive')

Mounted at /mnt/drive

In [8]:
import os
os.getcwd()
#os.listdir()
os.chdir('/mnt/drive/MyDrive/ciencia_de_datos')
os.listdir()

['netflix_data.csv',
 'democracy_data.csv',
 'democracy_data.gsheet',
 'output_file.csv',
 'regicor.csv',
 'customers_1.csv',
 'introduc_ciencia_de_datos',
 'billboard.csv',
 'datos_crudos.csv']

In [9]:
bill = pd.read_csv('billboard.csv')
dc = pd.read_csv('datos_crudos.csv')

In [38]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

In [5]:
df = pd.DataFrame({'Property':["House 1", "House 2", "House 3"],
                   'Price' : [0.8,0.4,0.8],
                   'Space' : [0.6,0.3,0.7],
                   'Location':[0.99, 0.2,0.4],
                   'Aestetics' : [0.5,0.6,0.8]})

In [6]:
df.head()

  Property  Price  Space  Location  Aestetics
0  House 1    0.8    0.6      0.99        0.5
1  House 2    0.4    0.3      0.20        0.6
2  House 3    0.8    0.7      0.40        0.8

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Property   3 non-null      object
 1   Price      3 non-null      float64
 2   Space      3 non-null      float64
 3   Location   3 non-null      float64
 4   Aestetics  3 non-null      float64
dtypes: float64(4), object(1)
memory usage: 252.0+ bytes

In [13]:
columns = df.columns
print(f'Las columnas son: ', columns)

Las columnas son:  Index(['Property', 'Price', 'Space', 'Location', 'Aestetics'], dtype='object')

Lo que queremos ahora es fusionar las variables que nos interesan para el estudio

In [19]:
df_long = pd.melt(frame=df, id_vars='Property', value_vars=columns, var_name='aspecto', value_name='valores')
df_long

   Property    aspecto  valores
0   House 1      Price     0.80
1   House 2      Price     0.40
2   House 3      Price     0.80
3   House 1      Space     0.60
4   House 2      Space     0.30
5   House 3      Space     0.70
6   House 1   Location     0.99
7   House 2   Location     0.20
8   House 3   Location     0.40
9   House 1  Aestetics     0.50
10  House 2  Aestetics     0.60
11  House 3  Aestetics     0.80

In [21]:
#De hecho lo podemos hacer mas rapido y directo
df_long_test = pd.melt(frame=df, id_vars='Property')
df_long_test

   Property   variable  value
0   House 1      Price   0.80
1   House 2      Price   0.40
2   House 3      Price   0.80
3   House 1      Space   0.60
4   House 2      Space   0.30
5   House 3      Space   0.70
6   House 1   Location   0.99
7   House 2   Location   0.20
8   House 3   Location   0.40
9   House 1  Aestetics   0.50
10  House 2  Aestetics   0.60
11  House 3  Aestetics   0.80

In [22]:
bill

,artist,track,date.entered,wk1,wk2,wk3,wk4,wk5,wk6,wk7,...,wk67,wk68,wk69,wk70,wk71,wk72,wk73,wk74,wk75,wk76
0,2 Pac,Baby Don't Cry (Keep...,2000-02-26,87,82.0,72.0,77.0,87.0,94.0,99.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2Ge+her,The Hardest Part Of ...,2000-09-02,91,87.0,92.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3 Doors Down,Kryptonite,2000-04-08,81,70.0,68.0,67.0,66.0,57.0,54.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3 Doors Down,Loser,2000-10-21,76,76.0,72.0,69.0,67.0,65.0,55.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,504 Boyz,Wobble Wobble,2000-04-15,57,34.0,25.0,17.0,17.0,31.0,36.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
312,Yankee Grey,Another Nine Minutes,2000-04-29,86,83.0,77.0,74.0,83.0,79.0,88.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
313,"Yearwood, Trisha",Real Live Woman,2000-04-01,85,83.0,83.0,82.0,81.0,91.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
314,Ying Yang Twins,Whistle While You Tw...,2000-03-18,95,94.0,91.0,85.0,84.0,78.0,74.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
315,Zombie Nation,Kernkraft 400,2000-09-02,99,99.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
316,matchbox twenty,Bent,2000-04-29,60,37.0,29.0,24.0,22.0,21.0,18.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [24]:
cols_bils = bill.columns
cols_bils

Index(['artist', 'track', 'date.entered', 'wk1', 'wk2', 'wk3', 'wk4', 'wk5',
       'wk6', 'wk7', 'wk8', 'wk9', 'wk10', 'wk11', 'wk12', 'wk13', 'wk14',
       'wk15', 'wk16', 'wk17', 'wk18', 'wk19', 'wk20', 'wk21', 'wk22', 'wk23',
       'wk24', 'wk25', 'wk26', 'wk27', 'wk28', 'wk29', 'wk30', 'wk31', 'wk32',
       'wk33', 'wk34', 'wk35', 'wk36', 'wk37', 'wk38', 'wk39', 'wk40', 'wk41',
       'wk42', 'wk43', 'wk44', 'wk45', 'wk46', 'wk47', 'wk48', 'wk49', 'wk50',
       'wk51', 'wk52', 'wk53', 'wk54', 'wk55', 'wk56', 'wk57', 'wk58', 'wk59',
       'wk60', 'wk61', 'wk62', 'wk63', 'wk64', 'wk65', 'wk66', 'wk67', 'wk68',
       'wk69', 'wk70', 'wk71', 'wk72', 'wk73', 'wk74', 'wk75', 'wk76'],
      dtype='object')

In [26]:
bill_long = pd.melt(bill, id_vars=['artist', 'track', 'date.entered'], value_vars=cols_bils[3:80])
bill_long

                 artist                    track date.entered variable  value
0                 2 Pac  Baby Don't Cry (Keep...   2000-02-26      wk1   87.0
1               2Ge+her  The Hardest Part Of ...   2000-09-02      wk1   91.0
2          3 Doors Down               Kryptonite   2000-04-08      wk1   81.0
3          3 Doors Down                    Loser   2000-10-21      wk1   76.0
4              504 Boyz            Wobble Wobble   2000-04-15      wk1   57.0
...                 ...                      ...          ...      ...    ...
24087       Yankee Grey     Another Nine Minutes   2000-04-29     wk76    NaN
24088  Yearwood, Trisha          Real Live Woman   2000-04-01     wk76    NaN
24089   Ying Yang Twins  Whistle While You Tw...   2000-03-18     wk76    NaN
24090     Zombie Nation            Kernkraft 400   2000-09-02     wk76    NaN
24091   matchbox twenty                     Bent   2000-04-29     wk76    NaN

[24092 rows x 5 columns]

In [28]:
bill_long.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24092 entries, 0 to 24091
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   artist        24092 non-null  object
 1   track         24092 non-null  object
 2   date.entered  24092 non-null  object
 3   variable      24092 non-null  object
 4   value         5307 non-null   float64
dtypes: float64(1), object(4)
memory usage: 941.2+ KB

In [34]:
bill_long['date.entered'] = pd.to_datetime(bill_long['date.entered'])
bill_long['year'] = bill_long['date.entered'].dt.year
bill_long['week'] = bill_long['date.entered'].dt.weekday
bill_long['month'] = bill_long['date.entered'].dt.month
bill_long

,artist,track,date.entered,variable,value,year,week,month
0,2 Pac,Baby Don't Cry (Keep...,2000-02-26,wk1,87.0,2000,5,2
1,2Ge+her,The Hardest Part Of ...,2000-09-02,wk1,91.0,2000,5,9
2,3 Doors Down,Kryptonite,2000-04-08,wk1,81.0,2000,5,4
3,3 Doors Down,Loser,2000-10-21,wk1,76.0,2000,5,10
4,504 Boyz,Wobble Wobble,2000-04-15,wk1,57.0,2000,5,4
...,...,...,...,...,...,...,...,...
24087,Yankee Grey,Another Nine Minutes,2000-04-29,wk76,NaN,2000,5,4
24088,"Yearwood, Trisha",Real Live Woman,2000-04-01,wk76,NaN,2000,5,4
24089,Ying Yang Twins,Whistle While You Tw...,2000-03-18,wk76,NaN,2000,5,3
24090,Zombie Nation,Kernkraft 400,2000-09-02,wk76,NaN,2000,5,9
24091,matchbox twenty,Bent,2000-04-29,wk76,NaN,2000,5,4

In [37]:
#Ahora, borrar datos
bill_long['value'].dropna(inplace=True)
bill_long.shape

(24092, 8)

In [1]:
bill_long(
    bill.melt(
      ic_vars = ['artist', 'track', 'date.entered'],
      var_name='variable'

    )
)

NameError: name 'bill_long' is not defined