<a href="https://colab.research.google.com/github/Juan-Vega18/-ANALISIS-EXPLOR-DE-DATOS---63510/blob/main/Salud_tarea_long_dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/mnt/drive')

Mounted at /mnt/drive

In [2]:
import os
os.getcwd()
#os.listdir()
os.chdir('/mnt/drive/MyDrive/ciencia_de_datos')
os.listdir()

['netflix_data.csv',
 'democracy_data.csv',
 'democracy_data.gsheet',
 'output_file.csv',
 'regicor.csv',
 'customers_1.csv',
 'introduc_ciencia_de_datos',
 'billboard.csv',
 'datos_crudos.csv',
 'Salud_Mental_20260412.csv']

In [3]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [37]:
df = pd.read_csv("Salud_Mental_20260412.csv") #Cargamos el archivo
df.head() #Visualizamos la estructura del dataframe (detectamos arreglo wide)

                                diagnostico_ingreso  ... Año diagnóstico
0           TRASTORNO MIXTO DE ANSIEDAD Y DEPRESION  ...            2023
1  EPISODIO DEPRESIVO GRAVE SIN SINTOMAS PSICOTICOS  ...            2023
2                       EPISODIO DEPRESIVO MODERADO  ...            2023
3       TRASTORNO AFECTIVO BIPOLAR, NO ESPECIFICADO  ...            2023
4                    ESQUIZOFRENIA, NO ESPECIFICADA  ...            2023

[5 rows x 12 columns]

In [5]:
df.info() #Revisamos la informacion del dataset

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 142 entries, 0 to 141
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   diagnostico_ingreso  142 non-null    object
 1   codigo_dx_ingreso    142 non-null    object
 2   Menor a 1            142 non-null    int64
 3   De 1 a 4             142 non-null    int64
 4   De 5 a 9             142 non-null    int64
 5   De 10 a 14           142 non-null    int64
 6   De 15 a 19           142 non-null    int64
 7   De 20 a 49           142 non-null    int64
 8   De 50 a 64           142 non-null    int64
 9   65 Y MAS             142 non-null    int64
 10  Total                142 non-null    int64
 11  Año diagnóstico      142 non-null    int64
dtypes: int64(10), object(2)
memory usage: 13.4+ KB

In [27]:
print(df.isnull().sum()) #Tenemos todas las casillas llenas, por lo que no tenemos necesidad de hacer un tratamiento de datos nulos.
print(df.columns) #revisamos que columnas tenemos

diagnostico_ingreso    0
codigo_dx_ingreso      0
Menor a 1              0
De 1 a 4               0
De 5 a 9               0
De 10 a 14             0
De 15 a 19             0
De 20 a 49             0
De 50 a 64             0
65 Y MAS               0
Total                  0
Año diagnóstico        0
dtype: int64
Index(['diagnostico_ingreso', 'codigo_dx_ingreso', 'Menor a 1', 'De 1 a 4',
       'De 5 a 9', 'De 10 a 14', 'De 15 a 19', 'De 20 a 49', 'De 50 a 64',
       '65 Y MAS', 'Total', 'Año diagnóstico'],
      dtype='object')

In [7]:
df['diagnostico_ingreso'] #Revisamos que enfermedades tenemos

0                TRASTORNO MIXTO DE ANSIEDAD Y DEPRESION
1       EPISODIO DEPRESIVO GRAVE SIN SINTOMAS PSICOTICOS
2                            EPISODIO DEPRESIVO MODERADO
3            TRASTORNO AFECTIVO BIPOLAR, NO ESPECIFICADO
4                         ESQUIZOFRENIA, NO ESPECIFICADA
                             ...
137    TRASTORNOS MENTALES Y DEL COMPORTAMIENTO DEBID...
138    TRASTORNOS MENTALES Y DEL COMPORTAMIENTO DEBID...
139    TRASTORNOS MENTALES Y DEL COMPORTAMIENTO DEBID...
140    TRASTORNOS MENTALES Y DEL COMPORTAMIENTO DEBID...
141    TRASTORNOS MENTALES Y DEL COMPORTAMIENTO DEBID...
Name: diagnostico_ingreso, Length: 142, dtype: object

In [42]:
df_cols_edades = ['De 1 a 4','De 5 a 9','De 10 a 14', 'De 15 a 19','De 20 a 49','De 50 a 64'] #definimos las columnas que nos interesan para la tarea
#El dataset está en formato wide(ancho), lo necesitamos en formato long.
df_long = df.melt( #Aplicamos la funcion melt para convertir nuestro dataset en formato long
    id_vars='diagnostico_ingreso', #id_vars ahora seran las enfermedades (diagnostico_ingreso)
    value_vars=df_cols_edades, #El value vars seran las columnas que previamente definimos, en este caso, los rangos de edad
    var_name='Edad_Rango', #Definimos el nombre de la segunda columna
    value_name='Casos' #Definimos el nombre de la 3er columna que será la cuenta de repetición de id_vars en Edad_Rango
)
df_long.loc[df_long.groupby('Edad_Rango')['Casos'].idxmax()] #Ya con el dataset en long, hacemos un groupby de Edad rango y casos, encontramos
# segun el diagnostico_ingreso los valores mas altos y los listamos. asi obtenemos las enfermedades que mas se repiten segun cada rango de edad.

                                  diagnostico_ingreso  Edad_Rango  Casos
111                         CONVULSIONES DISOCIATIVAS    De 1 a 4      1
371  EPISODIO DEPRESIVO GRAVE SIN SINTOMAS PSICOTICOS  De 10 a 14     21
513  EPISODIO DEPRESIVO GRAVE SIN SINTOMAS PSICOTICOS  De 15 a 19     23
568           TRASTORNO MIXTO DE ANSIEDAD Y DEPRESION  De 20 a 49     31
229  EPISODIO DEPRESIVO GRAVE SIN SINTOMAS PSICOTICOS    De 5 a 9      3
710           TRASTORNO MIXTO DE ANSIEDAD Y DEPRESION  De 50 a 64      8