<a href="https://colab.research.google.com/github/Juan-Vega18/-ANALISIS-EXPLOR-DE-DATOS---63510/blob/main/tarea_limpieza_de_datos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os
import numpy as np
from google.colab import drive
drive.mount('/mnt/drive', force_remount=True)

Mounted at /mnt/drive

In [ ]:
'''import os'''
'''os.getcwd()
#os.listdir()
os.chdir('/mnt/drive/MyDrive/ciencia_de_datos')
os.listdir()'''

"os.getcwd()\n#os.listdir()\nos.chdir('/mnt/drive/MyDrive/ciencia_de_datos')\nos.listdir()"

In [ ]:
df = pd.read_csv('/content/datos_crudos_tarea (1).csv') #Cargamos la data
df_copy = df.copy()

In [ ]:
df.head() #Tenemos la data en wide, la necesitamos en long.
df.drop(columns=['Unnamed: 0'], inplace=True) #Eliminamos Unnamed: 0, no la necesitamos para este estudio

In [ ]:
df

,id_paciente,fecha_consulta,edad,sexo,peso_kg,altura_m,presion_arterial,glucosa_mg_dL,colesterol_total,fuma,actividad_fisica,imc_calculado
0,524,2022-01-23 00:00:00,73,MUJER,80.6,2.38,89/97,NaN,-100,0,alta,NaN
1,603,2023-03-02 00:00:00,7,X,126.3,1.18,88/79,95,-100,0,Sedentario,NaN
2,527,2022-04-28 00:00:00,68,F,37.7,20,118/51,500,-100,no,Sedentario,NaN
3,32,2022-05-06 00:00:00,96,f,47.5,0.45,195/105,300,bueno,SI,Sedentario,NaN
4,617,2023-06-07 00:00:00,72,Mujer,198.8,0.81,126/87,85,120,0,Baja,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
1015,107,2022-12-22 00:00:00,-39,M,45.3,1.08,191/104,500,NaN,Fumador,Media,NaN
1016,271,2020-07-26 00:00:00,55,f,20.3,1.63,500/baja,500,600,No,2,NaN
1017,861,2020-04-02 00:00:00,20,X,5000,10,149/300,alto,350,0,0,NaN
1018,436,2021-10-18 00:00:00,69,m,154.2,1.17,127/baja,95,malo,no,alta,NaN
1019,103,2021-06-04 00:00:00,46,X,139.1,1.73,184/111,alto,-100,SI,alta,NaN

In [ ]:
print(df.shape)
print('*'*40)
print(df.dtypes)
print('*'*40)
print(df.duplicated().sum())
print('*'*40)
print(df.head())

(1020, 12)
****************************************
id_paciente           int64
fecha_consulta       object
edad                 object
sexo                 object
peso_kg              object
altura_m             object
presion_arterial     object
glucosa_mg_dL        object
colesterol_total     object
fuma                 object
actividad_fisica     object
imc_calculado       float64
dtype: object
****************************************
19
****************************************
   id_paciente       fecha_consulta edad   sexo peso_kg altura_m  \
0          524  2022-01-23 00:00:00   73  MUJER    80.6     2.38
1          603  2023-03-02 00:00:00    7      X   126.3     1.18
2          527  2022-04-28 00:00:00   68      F    37.7       20
3           32  2022-05-06 00:00:00   96      f    47.5     0.45
4          617  2023-06-07 00:00:00   72  Mujer   198.8     0.81

  presion_arterial glucosa_mg_dL colesterol_total fuma actividad_fisica  \
0            89/97           NaN             -100    0             alta
1            88/79            95             -100    0       Sedentario
2           118/51           500             -100   no       Sedentario
3          195/105           300            bueno   SI       Sedentario
4           126/87            85              120    0             Baja

   imc_calculado
0            NaN
1            NaN
2            NaN
3            NaN
4            NaN

In [ ]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id_paciente       1020 non-null   int64
 1   fecha_consulta    1020 non-null   object
 2   edad              1006 non-null   object
 3   sexo              917 non-null    object
 4   peso_kg           1006 non-null   object
 5   altura_m          1006 non-null   object
 6   presion_arterial  1020 non-null   object
 7   glucosa_mg_dL     923 non-null    object
 8   colesterol_total  886 non-null    object
 9   fuma              908 non-null    object
 10  actividad_fisica  929 non-null    object
 11  imc_calculado     0 non-null      float64
dtypes: float64(1), int64(1), object(10)
memory usage: 95.8+ KB
None

In [ ]:
print(df.isnull().sum()) #revisamos los nulls
df.columns #revisamos las columnas que tenemos

id_paciente            0
fecha_consulta         0
edad                  14
sexo                 103
peso_kg               14
altura_m              14
presion_arterial       0
glucosa_mg_dL         97
colesterol_total     134
fuma                 112
actividad_fisica      91
imc_calculado       1020
dtype: int64

Index(['id_paciente', 'fecha_consulta', 'edad', 'sexo', 'peso_kg', 'altura_m',
       'presion_arterial', 'glucosa_mg_dL', 'colesterol_total', 'fuma',
       'actividad_fisica', 'imc_calculado'],
      dtype='object')

In [ ]:
#Modificamos los nombres de las columnas por minusculas:
df.colums = (
    df.columns.str.strip().str.lower().str.replace(" ", "_").str.encode('ascii', errors='ignore').str.decode('ascii')
)
print(df.columns.tolist())

['id_paciente', 'fecha_consulta', 'edad', 'sexo', 'peso_kg', 'altura_m', 'presion_arterial', 'glucosa_mg_dL', 'colesterol_total', 'fuma', 'actividad_fisica', 'imc_calculado']

/tmp/ipykernel_1522/1360268307.py:2: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  df.colums = (

In [ ]:
df['fecha_consulta']

0       2022-01-23 00:00:00
1       2023-03-02 00:00:00
2       2022-04-28 00:00:00
3       2022-05-06 00:00:00
4       2023-06-07 00:00:00
               ...
1015    2022-12-22 00:00:00
1016    2020-07-26 00:00:00
1017    2020-04-02 00:00:00
1018    2021-10-18 00:00:00
1019    2021-06-04 00:00:00
Name: fecha_consulta, Length: 1020, dtype: object

In [ ]:
df['fecha_consulta'] = pd.to_datetime(df['fecha_consulta'])

ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.

ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/IPython/core/interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/tmp/ipykernel_1522/3577684628.py", line 1, in <cell line: 0>
    df['fecha_consulta'] = pd.to_datetime(df['fecha_consulta'])
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pandas/core/tools/datetimes.py", line 1067, in to_datetime
    values = convert_listlike(arg._values, format)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pandas/core/tools/datetimes.py", line 433, in _convert_listlike_datetimes
    return _array_strptime_with_fallback(arg, name, utc, format, exact, errors)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pandas/core/tools/datetimes.py", line 467, in _array_strptime_with_fallback
    result, tz_out = array_strptime(arg, fmt, exact=exact, errors=errors, utc=utc)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "strptime.pyx", line 501, in pandas._libs.tslibs.strptime.array_strptime
  File "strptime.pyx", line 451, in pandas._libs.tslibs.strptime.array_strptime
  File "strptime.pyx", line 583, in pandas._libs.tslibs.strptime._parse_with_format
ValueError: time data "2021/02/30" doesn't match format "%Y-%m-%d %H:%M:%S", at position 100. You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/IPython/core/interactiveshell.py", line 2099, in showtraceback
    stb = value._render_traceback_()
          ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ValueError' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/IPython/core/ultratb.py", line 1101, in get_records
    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/IPython/core/ultratb.py", line 248, in wrapped
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/IPython/core/ultratb.py", line 281, in _fixed_getinnerframes
    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/inspect.py", line 1769, in getinnerframes
    traceback_info = getframeinfo(tb, context)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/inspect.py", line 1714, in getframeinfo
    filename = getsourcefile(frame) or getfile(frame)
               ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/inspect.py", line 970, in getsourcefile
    module = getmodule(object, filename)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/inspect.py", line 999, in getmodule
    file = getabsfile(object, _filename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/inspect.py", line 983, in getabsfile
    return os.path.normcase(os.path.abspath(_filename))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen posixpath>", line 412, in abspath
OSError: [Errno 107] Transport endpoint is not connected
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/IPython/core/interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/tmp/ipykernel_1522/3577684628.py", line 1, in <cell line: 0>
    df['fecha_consulta'] = pd.to_datetime(df['fecha_consulta'])
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pandas/core/tools/datetimes.py", line 1067, in to_datetime
    values = convert_listlike(arg._values, format)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pandas/core/tools/datetimes.py", line 433, in _convert_listlike_datetimes
    return _array_strptime_with_fallback(arg, name, utc, format, exact, errors)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pandas/core/tools/datetimes.py", line 467, in _array_strptime_with_fallback
    result, tz_out = array_strptime(arg, fmt, exact=exact, errors=errors, utc=utc)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "strptime.pyx", line 501, in pandas._libs.tslibs.strptime.array_strptime
  File "strptime.pyx", line 451, in pandas._libs.tslibs.strptime.array_strptime
  File "strptime.pyx", line 583, in pandas._libs.tslibs.strptime._parse_with_format
ValueError: time data "2021/02/30" doesn't match format "%Y-%m-%d %H:%M:%S", at position 100. You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/IPython/core/interactiveshell.py", line 2099, in showtraceback
    stb = value._render_traceback_()
          ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ValueError' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/IPython/core/interactiveshell.py", line 3473, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/IPython/core/interactiveshell.py", line 3575, in run_code
    self.showtraceback(running_compiled_code=True)
  File "/usr/local/lib/python3.12/dist-packages/IPython/core/interactiveshell.py", line 2101, in showtraceback
    stb = self.InteractiveTB.structured_traceback(etype,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/IPython/core/ultratb.py", line 1367, in structured_traceback
    return FormattedTB.structured_traceback(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/IPython/core/ultratb.py", line 1267, in structured_traceback
    return VerboseTB.structured_traceback(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/IPython/core/ultratb.py", line 1124, in structured_traceback
    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/IPython/core/ultratb.py", line 1082, in format_exception_as_a_whole
    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/IPython/core/ultratb.py", line 382, in find_recursion
    return len(records), 0
           ^^^^^^^^^^^^
TypeError: object of type 'NoneType' has no len()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/IPython/core/interactiveshell.py", line 2099, in showtraceback
    stb = value._render_traceback_()
          ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TypeError' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/IPython/core/interactiveshell.py", line 3030, in _run_cell
    return runner(coro)
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/IPython/core/async_helpers.py", line 78, in _pseudo_sync_runner
    coro.send(None)
  File "/usr/local/lib/python3.12/dist-packages/IPython/core/interactiveshell.py", line 3257, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/IPython/core/interactiveshell.py", line 3492, in run_ast_nodes
    self.showtraceback()
  File "/usr/local/lib/python3.12/dist-packages/IPython/core/interactiveshell.py", line 2101, in showtraceback
    stb = self.InteractiveTB.structured_traceback(etype,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/IPython/core/ultratb.py", line 1367, in structured_traceback
    return FormattedTB.structured_traceback(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/IPython/core/ultratb.py", line 1267, in structured_traceback
    return VerboseTB.structured_traceback(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/IPython/core/ultratb.py", line 1142, in structured_traceback
    formatted_exceptions += self.format_exception_as_a_whole(etype, evalue, etb, lines_of_context,
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/IPython/core/ultratb.py", line 1089, in format_exception_as_a_whole
    filepath = os.path.abspath(filepath)
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen posixpath>", line 412, in abspath
OSError: [Errno 107] Transport endpoint is not connected

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/IPython/core/interactiveshell.py", line 2099, in showtraceback
    stb = value._render_traceback_()
          ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'OSError' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/IPython/core/ultratb.py", line 1101, in get_records
    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/IPython/core/ultratb.py", line 248, in wrapped
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/IPython/core/ultratb.py", line 281, in _fixed_getinnerframes
    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/inspect.py", line 1769, in getinnerframes
    traceback_info = getframeinfo(tb, context)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/inspect.py", line 1714, in getframeinfo
    filename = getsourcefile(frame) or getfile(frame)
               ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/inspect.py", line 970, in getsourcefile
    module = getmodule(object, filename)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/inspect.py", line 999, in getmodule
    file = getabsfile(object, _filename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/inspect.py", line 983, in getabsfile
    return os.path.normcase(os.path.abspath(_filename))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen posixpath>", line 412, in abspath
OSError: [Errno 107] Transport endpoint is not connected

Aqui nos damos cuenta de varias cosas y trucos del profe jeje (del dataset realmente). Resulta que tenemos unas fechas en diferente formato, y algunas otras imposibles.

Por ejemplo:
`time data "2021/02/30" doesn't match format "%Y-%m-%d %H:%M:%S", at position 100`

Esto literalmente es imposible ya que febrero no tiene dia 30...
Aparte el formato correcto es con `-` no con `/`, y algunos datos estan mixed. Asi que necesitamos hacer una limpieza mas profunda.

In [ ]:
df['fecha_consulta'] = pd.to_datetime(
    df['fecha_consulta'],
    errors='coerce',
    format='mixed'
)

¿Que hacen los dos parametros que fijamos?
1. `errors='coerce'` Lo que hace es convertir las fechas sin sentido como `2021/02/30` en `NaT` que significa `Not a Time`.
2. `format='mixed'` lo que hace es permitir multiples formatos, con guiones, `/`, incluso con las horas (nuestro caso)

In [ ]:
#Revisamos como quedó la columna
df['fecha_consulta'].isnull().sum() #Mas adelante veremos que hacer con los vacíos.

np.int64(10)

In [ ]:
#Dividimos la fecha en nuevas columnas por year, week, month
df['year'] = df['fecha_consulta'].dt.year
df['week'] = df['fecha_consulta'].dt.weekday
df['month'] = df['fecha_consulta'].dt.month
df

,id_paciente,fecha_consulta,edad,sexo,peso_kg,altura_m,presion_arterial,glucosa_mg_dL,colesterol_total,fuma,actividad_fisica,imc_calculado,year,week,month
0,524,2022-01-23,73,MUJER,80.6,2.38,89/97,NaN,-100,0,alta,NaN,2022.0,6.0,1.0
1,603,2023-03-02,7,X,126.3,1.18,88/79,95,-100,0,Sedentario,NaN,2023.0,3.0,3.0
2,527,2022-04-28,68,F,37.7,20,118/51,500,-100,no,Sedentario,NaN,2022.0,3.0,4.0
3,32,2022-05-06,96,f,47.5,0.45,195/105,300,bueno,SI,Sedentario,NaN,2022.0,4.0,5.0
4,617,2023-06-07,72,Mujer,198.8,0.81,126/87,85,120,0,Baja,NaN,2023.0,2.0,6.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1015,107,2022-12-22,-39,M,45.3,1.08,191/104,500,NaN,Fumador,Media,NaN,2022.0,3.0,12.0
1016,271,2020-07-26,55,f,20.3,1.63,500/baja,500,600,No,2,NaN,2020.0,6.0,7.0
1017,861,2020-04-02,20,X,5000,10,149/300,alto,350,0,0,NaN,2020.0,3.0,4.0
1018,436,2021-10-18,69,m,154.2,1.17,127/baja,95,malo,no,alta,NaN,2021.0,0.0,10.0
1019,103,2021-06-04,46,X,139.1,1.73,184/111,alto,-100,SI,alta,NaN,2021.0,4.0,6.0

In [ ]:
df_copy['sexo'].isnull().sum()
#Tenemos 103 nulls en el dataset original
df_copy['sexo'].value_counts()

sexo
M         115
f         110
Hombre    108
Mujer     106
m         102
MUJER      98
F          95
X          93
H          90
Name: count, dtype: int64

In [ ]:
#Ahora vamos con la columna sexo

print(df['sexo'].unique())
mapa_sex = {
    "m": 'M', "masculino": "M", "MASCULINO":'M',
    "f":'F','X':np.nan, 'Hombre':'M',
    'H':'M', 'Mujer':'F', 'MUJER':'F'
    }
df['sexo'] = df['sexo'].map(mapa_sex)
print(df['sexo'].value_counts(dropna=False))

['MUJER' 'X' 'F' 'f' 'Mujer' 'm' 'Hombre' 'M' nan 'H']
sexo
NaN    406
F      314
M      300
Name: count, dtype: int64

In [ ]:
#Ahora peso. Aplicamos el mismo estudio para el peso
print(df['peso_kg'].dtype)
print('#'*40)
print(df['peso_kg'].isnull().sum())
print('#'*40)
print(df['peso_kg'].duplicated())
print('#'*40)
print(df['peso_kg'].sample())
print('#'*40)
print(df['peso_kg'].head(30))
print('#'*40)
df_copy['peso_kg'].astype(str).str.strip().value_counts().head(30)

object
########################################
14
########################################
0       False
1       False
2       False
3       False
4       False
        ...
1015     True
1016    False
1017     True
1018     True
1019     True
Name: peso_kg, Length: 1020, dtype: bool
########################################
162    NaN
Name: peso_kg, dtype: object
########################################
0        80.6
1       126.3
2        37.7
3        47.5
4       198.8
5       104.7
6        18.2
7        92.7
8        93.9
9        73.4
10      -54.8
11      196.4
12      193.1
13      159.7
14       5000
15       24.4
16      149.5
17      148.3
18       20.9
19      105.7
20       44.6
21       98.0
22      177.2
23      183.2
24      173.9
25      129.9
26      199.5
27    setenta
28       26.6
29       29.6
Name: peso_kg, dtype: object
########################################

peso_kg
9999       21
1000       18
5000       16
noventa    16
nan        14
setenta    13
ochenta    11
12.8        5
73.4        4
165.8       4
149.0       4
139.8       3
29.4        3
40.6        3
187.9       3
134.0       3
181.8       3
117.5       3
25.8        3
133.0       3
26.1        3
20.1        3
167.6       3
114.1       3
127.2       3
47.5        2
90.9        2
154.2       2
-58.1       2
42.9        2
Name: count, dtype: int64

In [ ]:
peso = (
    df['peso_kg']
    .astype(str) #convertimos en str la column
    .str.strip() #quitamos espacios vacios antes y despues
    .str.lower() #convertimos a minusculas (dado que hay numeros en escrito)
    .str.replace(',','.',regex=False) #cambiamos comas por puntos
)

#Aqui seremos poco flexibles, vamos a tomar puramente los valores
#numericos
peso_num = pd.to_numeric(peso, errors='coerce') #Todo lo que no sea numerico se va a NaN

#Ahora, resolver el tema de los valores imposibles o absurdos
#df_copy['peso_kg'].unique()

Aqui nos damos cuenta que hay pesos pequeños, debemos fijar unos limites. Tenemos primero que resolver el tema de la edad, porque definir los limites de peso debe hacerse de forma responsable, porque cualquier peso positivo puede ser coherente si la edad es razonable y correspondiente. Entonces, vamos a dejar por ahora solo pesos positivos.

In [ ]:
peso_num = peso_num.where((peso_num > 0)
& (peso_num <= 300), np.nan)
df['peso_kg'] = peso_num

In [ ]:
print(df['peso_kg'].isnull().sum())
print(df['peso_kg'].describe())

189
count    831.000000
mean      98.209627
std       57.401262
min        2.000000
25%       48.050000
50%       96.100000
75%      147.100000
max      199.500000
Name: peso_kg, dtype: float64

In [ ]:
#Ahora edad (practicamente lo mismo)
#Ahora peso. Aplicamos el mismo estudio para el peso
print(df['edad'].dtype)
print('#'*40)
print(df['edad'].isnull().sum())
print('#'*40)
print(df['edad'].duplicated())
print('#'*40)
print(df['edad'].sample())
print('#'*40)
print(df['edad'].head(30))
print('#'*40)
df_copy['edad'].astype(str).str.strip().value_counts().head(30)

object
########################################
14
########################################
0       False
1       False
2       False
3       False
4       False
        ...
1015     True
1016     True
1017     True
1018     True
1019     True
Name: edad, Length: 1020, dtype: bool
########################################
51    69
Name: edad, dtype: object
########################################
0      73
1       7
2      68
3      96
4      72
5      48
6      37
7      55
8      72
9      13
10    150
11     10
12     -8
13     17
14     14
15    -16
16     85
17     99
18    104
19     75
20     93
21      5
22    999
23     85
24     20
25     20
26     45
27     82
28     90
29    105
Name: edad, dtype: object
########################################

edad
45             16
91             15
59             15
150            14
ochenta        14
200            14
67             14
nan            14
999            13
84             13
50             13
85             13
72             13
desconocido    13
25             13
noventa        13
9              12
104            12
10             12
39             12
36             12
14             12
69             11
37             11
73             11
57             11
1              11
46             11
6              11
74             11
Name: count, dtype: int64

In [ ]:
edad = (
    df['edad']
    .astype(str) #convertimos en str la column
    .str.strip() #quitamos espacios vacios antes y despues
    .str.lower() #convertimos a minusculas (dado que hay numeros en escrito)
    .str.replace(',','.',regex=False) #cambiamos comas por puntos
)

#Aqui seremos poco flexibles, vamos a tomar puramente los valores
#numericos
edad_num = pd.to_numeric(edad, errors='coerce') #Todo lo que no sea numerico se va a NaN
#invalidamos edades imposibles
edad_num = edad_num.where((edad_num >0) &
                          (peso_num <= 120),
                          np.nan)
df['edad'] = edad_num

In [ ]:
#Ahora vamos con altura.
altura = pd.to_numeric(df['altura_m'], errors='coerce')
altura = altura.where((altura > 0) & (altura <= 2.5), np.nan)
df['altura_m'] = altura

In [ ]:
#Ahora presion arterial
df['presion_arterial']

0          89/97
1          88/79
2         118/51
3        195/105
4         126/87
          ...
1015     191/104
1016    500/baja
1017     149/300
1018    127/baja
1019     184/111
Name: presion_arterial, Length: 1020, dtype: object

In [ ]:
#1 Debemos separar la presion en sistolica y diastolica
#en dos nuevas columnas

df[['presion_sistolica', 'presion_diastolica']] =(
    df['presion_arterial']
    .astype(str)
    .str.strip()
    .str.split('/', expand=True)
)

#Convertir todo en numerico, lo que no lo sea, de una a nan
df['presion_sistolica'] = pd.to_numeric(
    df['presion_sistolica'],
    errors='coerce'
)

df['presion_diastolica'] = pd.to_numeric(
    df['presion_diastolica'],
    errors='coerce'
)

In [ ]:
df.head()

,id_paciente,fecha_consulta,edad,sexo,peso_kg,altura_m,presion_arterial,glucosa_mg_dL,colesterol_total,fuma,actividad_fisica,imc_calculado,year,week,month,presion_sistolica,presion_diastolica
0,524,2022-01-23,73.0,F,80.6,2.38,89/97,NaN,-100,0,alta,NaN,2022.0,6.0,1.0,89.0,97.0
1,603,2023-03-02,NaN,NaN,126.3,1.18,88/79,95,-100,0,Sedentario,NaN,2023.0,3.0,3.0,88.0,79.0
2,527,2022-04-28,68.0,NaN,37.7,NaN,118/51,500,-100,no,Sedentario,NaN,2022.0,3.0,4.0,118.0,51.0
3,32,2022-05-06,96.0,F,47.5,0.45,195/105,300,bueno,SI,Sedentario,NaN,2022.0,4.0,5.0,195.0,105.0
4,617,2023-06-07,NaN,F,198.8,0.81,126/87,85,120,0,Baja,NaN,2023.0,2.0,6.0,126.0,87.0

Reglas que vamos a poner
Sistolica razonable (segun google, yo no se de esto)
Minima plausible viva: aprox 70
Maxima plausible extrema: aprox 300

Diastolica razonable:
minima plausible: aprox 40
maxima extrema: aprox 180

In [ ]:
df['presion_sistolica'] = df['presion_sistolica'].where(
    (df['presion_sistolica'] >= 70) &
    (df['presion_sistolica'] <= 300),
    np.nan
)

df['presion_diastolica'] = df['presion_diastolica'].where(
    (df['presion_diastolica'] >= 40) &
    (df['presion_diastolica'] <= 180),
    np.nan
)

In [ ]:
#La sistólica debe ser mayor a la diastolica (google dice esto)
#por lo tanto añadimos una nueva condicion

# sistolica > diastolica
mask = df['presion_sistolica'] <= df['presion_diastolica']

#Lo que no cumpla la mascara que pusimos automaticamente se va a NaN
df.loc[mask, ['presion_sistolica', 'presion_diastolica']] = np.nan

In [ ]:
df

,id_paciente,fecha_consulta,edad,sexo,peso_kg,altura_m,presion_arterial,glucosa_mg_dL,colesterol_total,fuma,actividad_fisica,imc_calculado,year,week,month,presion_sistolica,presion_diastolica
0,524,2022-01-23,73.0,F,80.6,2.38,89/97,NaN,-100,0,alta,NaN,2022.0,6.0,1.0,NaN,NaN
1,603,2023-03-02,NaN,NaN,126.3,1.18,88/79,95,-100,0,Sedentario,NaN,2023.0,3.0,3.0,88.0,79.0
2,527,2022-04-28,68.0,NaN,37.7,NaN,118/51,500,-100,no,Sedentario,NaN,2022.0,3.0,4.0,118.0,51.0
3,32,2022-05-06,96.0,F,47.5,0.45,195/105,300,bueno,SI,Sedentario,NaN,2022.0,4.0,5.0,195.0,105.0
4,617,2023-06-07,NaN,F,198.8,0.81,126/87,85,120,0,Baja,NaN,2023.0,2.0,6.0,126.0,87.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1015,107,2022-12-22,NaN,NaN,45.3,1.08,191/104,500,NaN,Fumador,Media,NaN,2022.0,3.0,12.0,191.0,104.0
1016,271,2020-07-26,55.0,F,20.3,1.63,500/baja,500,600,No,2,NaN,2020.0,6.0,7.0,NaN,NaN
1017,861,2020-04-02,NaN,NaN,NaN,NaN,149/300,alto,350,0,0,NaN,2020.0,3.0,4.0,149.0,NaN
1018,436,2021-10-18,NaN,M,154.2,1.17,127/baja,95,malo,no,alta,NaN,2021.0,0.0,10.0,127.0,NaN
1019,103,2021-06-04,NaN,NaN,139.1,1.73,184/111,alto,-100,SI,alta,NaN,2021.0,4.0,6.0,184.0,111.0

In [ ]:
#Ahora vamos con la glucosa.
#Ahora glucosa. Aplicamos el mismo estudio para la glucosa
print(df['glucosa_mg_dL'].dtype)
print('#'*40)
print(df['glucosa_mg_dL'].isnull().sum())
print('#'*40)
print(df['glucosa_mg_dL'].duplicated())
print('#'*40)
print(df['glucosa_mg_dL'].sample())
print('#'*40)
print(df['glucosa_mg_dL'].head(30))
print('#'*40)
df_copy['glucosa_mg_dL'].astype(str).str.strip().value_counts().head(30)

object
########################################
97
########################################
0       False
1       False
2       False
3       False
4       False
        ...
1015     True
1016     True
1017     True
1018     True
1019     True
Name: glucosa_mg_dL, Length: 1020, dtype: bool
########################################
577    bajo
Name: glucosa_mg_dL, dtype: object
########################################
0      NaN
1       95
2      500
3      300
4       85
5     bajo
6      500
7      110
8       95
9      180
10     500
11     NaN
12     -20
13     NaN
14    alto
15     -20
16     -20
17     110
18     500
19     NaN
20      85
21      50
22    bajo
23     -20
24      50
25     NaN
26     300
27     300
28      85
29      85
Name: glucosa_mg_dL, dtype: object
########################################

glucosa_mg_dL
300     108
bajo    108
nan      97
110      97
50       95
500      94
-20      89
180      88
95       82
85       82
alto     80
Name: count, dtype: int64

La columna de `glucosa_mg_dL` esta fuertemente contaminada con un monton de errores, por ejemplo, cuando hacemos el value_counts, nos encontramos que hay valores negativos, valores como (alto, bajo) que no nos sirven como caracterisitca numerica, o NaN, tambien valores muy altos como:
300 (extremo pero posible en crisis)
500 (muy extremo, raro pero médicamente posible)

In [ ]:
glucosa = (
    df['glucosa_mg_dL']
    .astype(str)
    .str.strip()
    .str.lower()
)
glucosa = glucosa.replace({
    'alto': np.nan,
    'bajo': np.nan,
    'nan': np.nan
})
glucosa = pd.to_numeric(glucosa, errors='coerce')

glucosa = glucosa.where(
    (glucosa >= 20) & (glucosa <= 600),
    np.nan
)
#<20 casi imposible con una persona viva
#>600 muy raro, lo tomaremos como error
df['glucosa_mg_dL'] = glucosa

In [ ]:
#Hacemos la revision del dataset original y el cambio que obtuvimos al hacer el
#reemplazo de los valores invalidos
print(df_copy['glucosa_mg_dL'].describe())
print(df_copy['glucosa_mg_dL'].isnull().sum())
print('#'*40)
print(df['glucosa_mg_dL'].describe())
print(df['glucosa_mg_dL'].isnull().sum())

count      923
unique      10
top       bajo
freq       108
Name: glucosa_mg_dL, dtype: object
97
########################################
count    646.000000
mean     194.148607
std      149.753191
min       50.000000
25%       85.000000
50%      110.000000
75%      300.000000
max      500.000000
Name: glucosa_mg_dL, dtype: float64
374

In [ ]:
#Ahora vamos con colesterol_total
print(df['colesterol_total'].dtype)
print('#'*40)
print(df['colesterol_total'].isnull().sum())
print('#'*40)
print(df['colesterol_total'].duplicated())
print('#'*40)
print(df['colesterol_total'].sample())
print('#'*40)
print(df['colesterol_total'].head(30))
print('#'*40)
df_copy['colesterol_total'].astype(str).str.strip().value_counts().head(30)

object
########################################
134
########################################
0       False
1        True
2        True
3       False
4       False
        ...
1015     True
1016     True
1017     True
1018     True
1019     True
Name: colesterol_total, Length: 1020, dtype: bool
########################################
904    600
Name: colesterol_total, dtype: object
########################################
0      -100
1      -100
2      -100
3     bueno
4       120
5       350
6       120
7       200
8       NaN
9      -100
10    bueno
11     malo
12      120
13      120
14      350
15      200
16      350
17    bueno
18      600
19     -100
20      600
21      600
22     -100
23      120
24      120
25      600
26      NaN
27      200
28      600
29      350
Name: colesterol_total, dtype: object
########################################

colesterol_total
bueno    144
nan      134
malo     130
600      130
120      127
-100     123
350      117
200      115
Name: count, dtype: int64

Vamos a dejar los 'bueno - malo' eso no sirve, vamos a quitar los negativos tambien

In [ ]:
col = (
    df_copy['colesterol_total']
    .astype(str)
    .str.strip()
    .str.lower()
)
col = col.replace({ #reemplazamos las caracteristicas de texto ambiguas
    'bueno': np.nan,
    'malo': np.nan,
    'nan': np.nan
})

# convertir a numérico
col = pd.to_numeric(col, errors='coerce') #convertimos a numerico todo

# invalidar imposibles
col = col.where((col >= 50) & (col <= 1000), np.nan) #lo que no cumpla con 2 estandares (el minimo lo fijamos
#en 50 y el maximo posible vivo es 1000)

df['colesterol_total'] = col #metemos todo al dataset

In [ ]:
#Hacemos la revision del dataset original y el cambio que obtuvimos al hacer el
#reemplazo de los valores invalidos
print(df_copy['colesterol_total'].describe())
print(df_copy['colesterol_total'].isnull().sum())
print('#'*40)
print(df['colesterol_total'].describe())
print(df['colesterol_total'].isnull().sum())

count       886
unique        7
top       bueno
freq        144
Name: colesterol_total, dtype: object
134
########################################
count    489.000000
mean     321.451943
std      186.821280
min      120.000000
25%      120.000000
50%      350.000000
75%      600.000000
max      600.000000
Name: colesterol_total, dtype: float64
531

In [ ]:
df['colesterol_total']

0         NaN
1         NaN
2         NaN
3         NaN
4       120.0
        ...
1015      NaN
1016    600.0
1017    350.0
1018      NaN
1019      NaN
Name: colesterol_total, Length: 1020, dtype: float64

In [ ]:
#Ahora vamos con fuma
#Ahora vamos con colesterol_total
print(df['fuma'].dtype)
print('#'*40)
print(df['fuma'].isnull().sum())
print('#'*40)
print(df['fuma'].duplicated())
print('#'*40)
print(df['fuma'].sample())
print('#'*40)
print(df['fuma'].head(30))
print('#'*40)
df_copy['fuma'].astype(str).str.strip().value_counts().head(30)

object
########################################
112
########################################
0       False
1        True
2       False
3       False
4        True
        ...
1015     True
1016     True
1017     True
1018     True
1019     True
Name: fuma, Length: 1020, dtype: bool
########################################
919    1
Name: fuma, dtype: object
########################################
0           0
1           0
2          no
3          SI
4           0
5          no
6     Fumador
7     Fumador
8          NO
9     Fumador
10         SI
11         No
12          1
13          0
14          0
15    Fumador
16         Sí
17         no
18    Fumador
19          1
20         no
21          0
22         no
23          0
24    Fumador
25         No
26        NaN
27         No
28          0
29         Sí
Name: fuma, dtype: object
########################################

fuma
no         113
0          112
nan        112
No         108
Sí         105
SI         104
NO         102
Fumador     96
1           86
si          82
Name: count, dtype: int64

In [ ]:
fuma = (
    df['fuma'] #accedemos a la columna
    .astype(str)
    .str.strip()
    .str.lower()
)

mapa_fuma = { #aplicamos el mapa segun las caracteristicas del dataset
    'sí': 1,
    'si': 1,
    '1': 1,
    'fumador': 1,
    'no': 0,
    '0': 0,
    'nan': np.nan
}
df['fuma'] = fuma.map(mapa_fuma) #metemos los cambios en el dataset

print(df_copy['fuma'].value_counts(dropna=False)) #revisamos el original
print(df['fuma'].value_counts(dropna=False))

fuma
no         113
0          112
NaN        112
No         108
Sí         105
SI         104
NO         102
Fumador     96
1           86
si          82
Name: count, dtype: int64
fuma
1.0    473
0.0    435
NaN    112
Name: count, dtype: int64

In [ ]:
df['fuma']

0       0.0
1       0.0
2       0.0
3       1.0
4       0.0
       ...
1015    1.0
1016    0.0
1017    0.0
1018    0.0
1019    1.0
Name: fuma, Length: 1020, dtype: float64

In [ ]:
df

,id_paciente,fecha_consulta,edad,sexo,peso_kg,altura_m,presion_arterial,glucosa_mg_dL,colesterol_total,fuma,actividad_fisica,imc_calculado,year,week,month,presion_sistolica,presion_diastolica
0,524,2022-01-23,73.0,F,80.6,2.38,89/97,NaN,NaN,0.0,alta,NaN,2022.0,6.0,1.0,NaN,NaN
1,603,2023-03-02,NaN,NaN,126.3,1.18,88/79,95.0,NaN,0.0,Sedentario,NaN,2023.0,3.0,3.0,88.0,79.0
2,527,2022-04-28,68.0,NaN,37.7,NaN,118/51,500.0,NaN,0.0,Sedentario,NaN,2022.0,3.0,4.0,118.0,51.0
3,32,2022-05-06,96.0,F,47.5,0.45,195/105,300.0,NaN,1.0,Sedentario,NaN,2022.0,4.0,5.0,195.0,105.0
4,617,2023-06-07,NaN,F,198.8,0.81,126/87,85.0,120.0,0.0,Baja,NaN,2023.0,2.0,6.0,126.0,87.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1015,107,2022-12-22,NaN,NaN,45.3,1.08,191/104,500.0,NaN,1.0,Media,NaN,2022.0,3.0,12.0,191.0,104.0
1016,271,2020-07-26,55.0,F,20.3,1.63,500/baja,500.0,600.0,0.0,2,NaN,2020.0,6.0,7.0,NaN,NaN
1017,861,2020-04-02,NaN,NaN,NaN,NaN,149/300,NaN,350.0,0.0,0,NaN,2020.0,3.0,4.0,149.0,NaN
1018,436,2021-10-18,NaN,M,154.2,1.17,127/baja,95.0,NaN,0.0,alta,NaN,2021.0,0.0,10.0,127.0,NaN
1019,103,2021-06-04,NaN,NaN,139.1,1.73,184/111,NaN,NaN,1.0,alta,NaN,2021.0,4.0,6.0,184.0,111.0

In [ ]:
#Actividad fisica
print(df['actividad_fisica'].dtype)
print('#'*40)
print(df['actividad_fisica'].isnull().sum())
print('#'*40)
print(df['actividad_fisica'].duplicated())
print('#'*40)
print(df['actividad_fisica'].sample())
print('#'*40)
print(df['actividad_fisica'].head(30))
print('#'*40)
df_copy['actividad_fisica'].astype(str).str.strip().value_counts().head(30)

object
########################################
91
########################################
0       False
1       False
2        True
3        True
4       False
        ...
1015     True
1016     True
1017     True
1018     True
1019     True
Name: actividad_fisica, Length: 1020, dtype: bool
########################################
129    Sedentario
Name: actividad_fisica, dtype: object
########################################
0           alta
1     Sedentario
2     Sedentario
3     Sedentario
4           Baja
5              0
6           baja
7           Alta
8            NaN
9              1
10         Media
11             1
12          Baja
13             1
14             1
15         Media
16          baja
17             0
18           NaN
19           NaN
20           NaN
21             1
22          Alta
23           NaN
24             1
25          Alta
26             2
27             2
28             0
29          Baja
Name: actividad_fisica, dtype: object
########################################

actividad_fisica
Media         111
alta          101
1              98
2              97
Alta           95
Baja           93
nan            91
0              89
baja           85
media          85
Sedentario     75
Name: count, dtype: int64

In [ ]:
act = (
    df['actividad_fisica']
    .astype(str)
    .str.strip()
    .str.lower()
)
#Aqui vamos a aplicar una categórica ordinal con 4 niveles, 0 = sedentario, 1 = baja, 2 = media, 3 = alta
#esto para poder hacer un buen analisis, aunque tambien podriamos dejarlo como si fueran categorias de texto
mapa_act = { #aplicamos el mapa de las catacteristicas
    'sedentario': 0,
    'baja': 1,
    '0': 1,
    'media': 2,
    '1': 2,
    'alta': 3,
    '2': 3,
    'nan': np.nan
}

df['actividad_fisica'] = act.map(mapa_act) #aplicamos el mapa
print(df_copy['actividad_fisica'].value_counts(dropna=False)) #original
print('#'*40)
print(df['actividad_fisica'].value_counts(dropna=False)) #modificado

actividad_fisica
Media         111
alta          101
1              98
2              97
Alta           95
Baja           93
NaN            91
0              89
baja           85
media          85
Sedentario     75
Name: count, dtype: int64
########################################
actividad_fisica
2.0    294
3.0    293
1.0    267
NaN     91
0.0     75
Name: count, dtype: int64

In [ ]:
df

,id_paciente,fecha_consulta,edad,sexo,peso_kg,altura_m,presion_arterial,glucosa_mg_dL,colesterol_total,fuma,actividad_fisica,imc_calculado,year,week,month,presion_sistolica,presion_diastolica
0,524,2022-01-23,73.0,F,80.6,2.38,89/97,NaN,NaN,0.0,3.0,NaN,2022.0,6.0,1.0,NaN,NaN
1,603,2023-03-02,NaN,NaN,126.3,1.18,88/79,95.0,NaN,0.0,0.0,NaN,2023.0,3.0,3.0,88.0,79.0
2,527,2022-04-28,68.0,NaN,37.7,NaN,118/51,500.0,NaN,0.0,0.0,NaN,2022.0,3.0,4.0,118.0,51.0
3,32,2022-05-06,96.0,F,47.5,0.45,195/105,300.0,NaN,1.0,0.0,NaN,2022.0,4.0,5.0,195.0,105.0
4,617,2023-06-07,NaN,F,198.8,0.81,126/87,85.0,120.0,0.0,1.0,NaN,2023.0,2.0,6.0,126.0,87.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1015,107,2022-12-22,NaN,NaN,45.3,1.08,191/104,500.0,NaN,1.0,2.0,NaN,2022.0,3.0,12.0,191.0,104.0
1016,271,2020-07-26,55.0,F,20.3,1.63,500/baja,500.0,600.0,0.0,3.0,NaN,2020.0,6.0,7.0,NaN,NaN
1017,861,2020-04-02,NaN,NaN,NaN,NaN,149/300,NaN,350.0,0.0,1.0,NaN,2020.0,3.0,4.0,149.0,NaN
1018,436,2021-10-18,NaN,M,154.2,1.17,127/baja,95.0,NaN,0.0,3.0,NaN,2021.0,0.0,10.0,127.0,NaN
1019,103,2021-06-04,NaN,NaN,139.1,1.73,184/111,NaN,NaN,1.0,3.0,NaN,2021.0,4.0,6.0,184.0,111.0

Por ultimo vamos a calcular el imc con todo el dataset limpio... luego, borraremos las filas vacias con alguna estrategia.
IMC = peso(kg)/altura^2 (m)

In [ ]:
df['imc_calculado'] = np.where(
    (df['peso_kg'].notna()) & #los no vacios
    (df['altura_m'].notna()), #los no vacios
    df['peso_kg'] / (df['altura_m'] ** 2),
    np.nan
).round(2)

In [ ]:
df['imc_calculado']

0        14.23
1        90.71
2          NaN
3       234.57
4       303.00
         ...
1015     38.84
1016      7.64
1017       NaN
1018    112.65
1019     46.48
Name: imc_calculado, Length: 1020, dtype: float64

In [ ]:
df

,id_paciente,fecha_consulta,edad,sexo,peso_kg,altura_m,presion_arterial,glucosa_mg_dL,colesterol_total,fuma,actividad_fisica,imc_calculado,year,week,month,presion_sistolica,presion_diastolica
0,524,2022-01-23,73.0,F,80.6,2.38,89/97,NaN,NaN,0.0,3.0,14.23,2022.0,6.0,1.0,NaN,NaN
1,603,2023-03-02,NaN,NaN,126.3,1.18,88/79,95.0,NaN,0.0,0.0,90.71,2023.0,3.0,3.0,88.0,79.0
2,527,2022-04-28,68.0,NaN,37.7,NaN,118/51,500.0,NaN,0.0,0.0,NaN,2022.0,3.0,4.0,118.0,51.0
3,32,2022-05-06,96.0,F,47.5,0.45,195/105,300.0,NaN,1.0,0.0,234.57,2022.0,4.0,5.0,195.0,105.0
4,617,2023-06-07,NaN,F,198.8,0.81,126/87,85.0,120.0,0.0,1.0,303.00,2023.0,2.0,6.0,126.0,87.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1015,107,2022-12-22,NaN,NaN,45.3,1.08,191/104,500.0,NaN,1.0,2.0,38.84,2022.0,3.0,12.0,191.0,104.0
1016,271,2020-07-26,55.0,F,20.3,1.63,500/baja,500.0,600.0,0.0,3.0,7.64,2020.0,6.0,7.0,NaN,NaN
1017,861,2020-04-02,NaN,NaN,NaN,NaN,149/300,NaN,350.0,0.0,1.0,NaN,2020.0,3.0,4.0,149.0,NaN
1018,436,2021-10-18,NaN,M,154.2,1.17,127/baja,95.0,NaN,0.0,3.0,112.65,2021.0,0.0,10.0,127.0,NaN
1019,103,2021-06-04,NaN,NaN,139.1,1.73,184/111,NaN,NaN,1.0,3.0,46.48,2021.0,4.0,6.0,184.0,111.0

In [ ]:
df.columns

Index(['id_paciente', 'fecha_consulta', 'edad', 'sexo', 'peso_kg', 'altura_m',
       'presion_arterial', 'glucosa_mg_dL', 'colesterol_total', 'fuma',
       'actividad_fisica', 'imc_calculado', 'year', 'week', 'month',
       'presion_sistolica', 'presion_diastolica'],
      dtype='object')

In [ ]:
df.drop(columns=['presion_arterial', 'fecha_consulta'], inplace=True)

In [ ]:
df

,id_paciente,edad,sexo,peso_kg,altura_m,glucosa_mg_dL,colesterol_total,fuma,actividad_fisica,imc_calculado,year,week,month,presion_sistolica,presion_diastolica
0,524,73.0,F,80.6,2.38,NaN,NaN,0.0,3.0,14.23,2022.0,6.0,1.0,NaN,NaN
1,603,NaN,NaN,126.3,1.18,95.0,NaN,0.0,0.0,90.71,2023.0,3.0,3.0,88.0,79.0
2,527,68.0,NaN,37.7,NaN,500.0,NaN,0.0,0.0,NaN,2022.0,3.0,4.0,118.0,51.0
3,32,96.0,F,47.5,0.45,300.0,NaN,1.0,0.0,234.57,2022.0,4.0,5.0,195.0,105.0
4,617,NaN,F,198.8,0.81,85.0,120.0,0.0,1.0,303.00,2023.0,2.0,6.0,126.0,87.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1015,107,NaN,NaN,45.3,1.08,500.0,NaN,1.0,2.0,38.84,2022.0,3.0,12.0,191.0,104.0
1016,271,55.0,F,20.3,1.63,500.0,600.0,0.0,3.0,7.64,2020.0,6.0,7.0,NaN,NaN
1017,861,NaN,NaN,NaN,NaN,NaN,350.0,0.0,1.0,NaN,2020.0,3.0,4.0,149.0,NaN
1018,436,NaN,M,154.2,1.17,95.0,NaN,0.0,3.0,112.65,2021.0,0.0,10.0,127.0,NaN
1019,103,NaN,NaN,139.1,1.73,NaN,NaN,1.0,3.0,46.48,2021.0,4.0,6.0,184.0,111.0

In [ ]:
#Revision final del dataset
#ORIGINAL
print(df_copy.info())
print(df_copy.isnull().sum())
print(df_copy.describe())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        1020 non-null   int64
 1   id_paciente       1020 non-null   int64
 2   fecha_consulta    1020 non-null   object
 3   edad              1006 non-null   object
 4   sexo              917 non-null    object
 5   peso_kg           1006 non-null   object
 6   altura_m          1006 non-null   object
 7   presion_arterial  1020 non-null   object
 8   glucosa_mg_dL     923 non-null    object
 9   colesterol_total  886 non-null    object
 10  fuma              908 non-null    object
 11  actividad_fisica  929 non-null    object
 12  imc_calculado     0 non-null      float64
dtypes: float64(1), int64(2), object(10)
memory usage: 103.7+ KB
None
Unnamed: 0             0
id_paciente            0
fecha_consulta         0
edad                  14
sexo                 103
peso_kg               14
altura_m              14
presion_arterial       0
glucosa_mg_dL         97
colesterol_total     134
fuma                 112
actividad_fisica      91
imc_calculado       1020
dtype: int64
        Unnamed: 0  id_paciente  imc_calculado
count  1020.000000  1020.000000            0.0
mean    509.500000   502.918627            NaN
std     294.592939   288.735731            NaN
min       0.000000     1.000000            NaN
25%     254.750000   253.750000            NaN
50%     509.500000   505.500000            NaN
75%     764.250000   752.250000            NaN
max    1019.000000  1000.000000            NaN

In [ ]:
#MODIFICADO Y AJUSTADO
print(df.info())
print(df.isnull().sum())
print(df.describe())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   id_paciente         1020 non-null   int64
 1   edad                442 non-null    float64
 2   sexo                614 non-null    object
 3   peso_kg             831 non-null    float64
 4   altura_m            812 non-null    float64
 5   glucosa_mg_dL       646 non-null    float64
 6   colesterol_total    489 non-null    float64
 7   fuma                908 non-null    float64
 8   actividad_fisica    929 non-null    float64
 9   imc_calculado       671 non-null    float64
 10  year                1010 non-null   float64
 11  week                1010 non-null   float64
 12  month               1010 non-null   float64
 13  presion_sistolica   856 non-null    float64
 14  presion_diastolica  846 non-null    float64
dtypes: float64(13), int64(1), object(1)
memory usage: 119.7+ KB
None
id_paciente             0
edad                  578
sexo                  406
peso_kg               189
altura_m              208
glucosa_mg_dL         374
colesterol_total      531
fuma                  112
actividad_fisica       91
imc_calculado         349
year                   10
week                   10
month                  10
presion_sistolica     164
presion_diastolica    174
dtype: int64
       id_paciente        edad     peso_kg    altura_m  glucosa_mg_dL  \
count  1020.000000  442.000000  831.000000  812.000000     646.000000
mean    502.918627   67.384615   98.209627    1.443411     194.148607
std     288.735731  106.429803   57.401262    0.610118     149.753191
min       1.000000    1.000000    2.000000    0.400000      50.000000
25%     253.750000   28.250000   48.050000    0.917500      85.000000
50%     505.500000   53.000000   96.100000    1.440000     110.000000
75%     752.250000   84.000000  147.100000    1.980000     300.000000
max    1000.000000  999.000000  199.500000    2.500000     500.000000

       colesterol_total        fuma  actividad_fisica  imc_calculado  \
count        489.000000  908.000000        929.000000     671.000000
mean         321.451943    0.520925          1.866523     100.969508
std          186.821280    0.499837          0.953357     153.537494
min          120.000000    0.000000          0.000000       0.390000
25%          120.000000    0.000000          1.000000      20.730000
50%          350.000000    1.000000          2.000000      40.360000
75%          600.000000    1.000000          3.000000     112.700000
max          600.000000    1.000000          3.000000    1052.150000

              year         week        month  presion_sistolica  \
count  1010.000000  1010.000000  1010.000000         856.000000
mean   2021.589109     3.028713     6.418812         153.873832
std       1.103414     2.004002     3.485186          37.586429
min    2020.000000     0.000000     1.000000          80.000000
25%    2021.000000     1.000000     3.000000         123.000000
50%    2022.000000     3.000000     6.000000         156.000000
75%    2023.000000     5.000000    10.000000         186.000000
max    2023.000000     6.000000    12.000000         219.000000

       presion_diastolica
count          846.000000
mean            82.513002
std             19.669318
min             50.000000
25%             66.000000
50%             81.000000
75%             99.000000
max            119.000000