<a href="https://colab.research.google.com/github/Juan-Vega18/-ANALISIS-EXPLOR-DE-DATOS---63510/blob/main/TAREA_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from google.colab import drive
drive.mount('/mnt/drive')

Mounted at /mnt/drive

In [3]:
import os
os.getcwd()
#os.listdir()
os.chdir('/mnt/drive/MyDrive/ciencia_de_datos')
os.listdir()

['netflix_data.csv',
 'democracy_data.csv',
 'democracy_data.gsheet',
 'output_file.csv',
 'regicor.csv']

In [4]:
import pandas as pd

In [5]:
df = pd.read_csv('democracy_data.csv')
df.head()
#df.tail(5)
df.shape

(14768, 44)

#1. SOLUCIÓN TAREA 2 F-STRINGS
#La presidenta de un pais democratico que tenga el mas largo periodo como gobernante.

In [7]:
#1 Dataframe presidenta female y pais democratico

df_fem_dem = df[(df['is_female_president'] == True) & (df['is_democracy'] == True)]
df_fem_dem.head()
#df_fem_dem.shape
df_fem_dem

,Unnamed: 0,country_name,country_code,year,regime_category_index,regime_category,is_monarchy,is_commonwealth,monarch_name,monarch_accession_year,...,electoral_category_index,electoral_category,spatial_electoral,has_alternation,is_multiparty,has_free_and_fair_election,parliamentary_election_year,election_month,election_year,has_postponed_election
451,452,Argentina,ARG,1975,2.0,Presidential democracy,False,False,NaN,NaN,...,3.0,democratic elections,0.800000,True,True,True,0.0,NaN,NaN,False
484,485,Argentina,ARG,2008,2.0,Presidential democracy,False,False,NaN,NaN,...,3.0,democratic elections,3.000000,True,True,True,1.0,October,2007.0,False
485,486,Argentina,ARG,2009,2.0,Presidential democracy,False,False,NaN,NaN,...,3.0,democratic elections,3.000000,True,True,True,0.0,NaN,NaN,False
486,487,Argentina,ARG,2010,2.0,Presidential democracy,False,False,NaN,NaN,...,3.0,democratic elections,3.000000,True,True,True,0.0,NaN,NaN,False
487,488,Argentina,ARG,2011,2.0,Presidential democracy,False,False,NaN,NaN,...,3.0,democratic elections,3.000000,True,True,True,0.0,NaN,NaN,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12920,12921,Taiwan,TWN,2019,1.0,Mixed democratic,False,False,NaN,NaN,...,3.0,democratic elections,2.000000,True,True,True,0.0,NaN,NaN,False
12921,12922,Taiwan,TWN,2020,1.0,Mixed democratic,False,False,NaN,NaN,...,3.0,democratic elections,2.000000,True,True,True,1.0,January,2020.0,False
13416,13417,Trinidad &Tobago,TTO,2018,0.0,Parliamentary democracy,False,True,NaN,NaN,...,3.0,democratic elections,2.333333,True,True,True,0.0,NaN,NaN,False
13417,13418,Trinidad &Tobago,TTO,2019,0.0,Parliamentary democracy,False,True,NaN,NaN,...,3.0,democratic elections,2.333333,True,True,True,0.0,NaN,NaN,False
13418,13419,Trinidad &Tobago,TTO,2020,0.0,Parliamentary democracy,False,True,NaN,NaN,...,3.0,democratic elections,2.333333,True,True,True,0.0,NaN,NaN,False

Para resolver el problema de los años, debo encontrar diferentes soluciones, seguramente habrá alguna mas ingeniosas que otras pero considero que los metodos iterativos para bases de datos no son los mas ingeniosos... Podrian tardarse demasiado y requierir una gran cantidad de computo.

Veo que cada dato por pais está desde 1950 a 2020, pensaba en contar la cantidad de veces que sale el nombre de una de las presidentas, pero eso no podría garantizar que sean periodos continuos de presidencia.


Algo que si noto es que la columna importante es 'election_year' alterna entre NA y el año. cuando hay un cambio entre NA y un valor int es porque hubo un cambio de presidente o una reelección, si o si, entonces, primer paso interesante, retirar los NA (específicos de esa columna), y luego vamos a comparar los años.

In [11]:
df_yr_na = df_fem_dem.dropna(subset='election_year')
#df_yr_na.to_csv('output_file.csv', index=False)
#save

df_yr_na.head()

,Unnamed: 0,country_name,country_code,year,regime_category_index,regime_category,is_monarchy,is_commonwealth,monarch_name,monarch_accession_year,...,electoral_category_index,electoral_category,spatial_electoral,has_alternation,is_multiparty,has_free_and_fair_election,parliamentary_election_year,election_month,election_year,has_postponed_election
484,485,Argentina,ARG,2008,2.0,Presidential democracy,False,False,NaN,NaN,...,3.0,democratic elections,3.000,True,True,True,1.0,October,2007.0,False
488,489,Argentina,ARG,2012,2.0,Presidential democracy,False,False,NaN,NaN,...,3.0,democratic elections,3.000,True,True,True,1.0,October,2015.0,False
1836,1837,Brazil,BRA,2011,2.0,Presidential democracy,False,False,NaN,NaN,...,3.0,democratic elections,2.875,True,True,True,1.0,October,2010.0,False
1840,1841,Brazil,BRA,2015,2.0,Presidential democracy,False,False,NaN,NaN,...,3.0,democratic elections,3.000,True,True,True,1.0,October,2014.0,False
2754,2755,Chile,CHL,2006,2.0,Presidential democracy,False,False,NaN,NaN,...,3.0,democratic elections,3.000,True,True,True,1.0,December,2005.0,False

Ya que tenemos los valores unicos, tenemos que comparar los subunicos nombres, es decir, buscamos una clave de nombre especifica (verificar si la columna de nombres es categórica), luego de eso, dado que quitamos los NA, podemos garantizar que entre el ultimo nombre y el 3er nombre

In [99]:
print(df_yr_na['president_name'].dtype)

category

In [100]:
#Cambiamos a categorías
df_yr_na['president_name'] = df_yr_na['president_name'].astype('category')
#print(df_yr_na['president_name'].dtype)
#print(df_yr_na['election_year'].dtype)
#Cambiamos años a int
df_yr_na['election_year'] = df_yr_na['election_year'].astype(int)
print(df_yr_na['election_year'].dtype)
#df_yr_na['president_name'].unique() #Tenemos 30 presidentas unicas.

int64

/tmp/ipykernel_1495/2564169016.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_yr_na['president_name'] = df_yr_na['president_name'].astype('category')
/tmp/ipykernel_1495/2564169016.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_yr_na['election_year'] = df_yr_na['election_year'].astype(int)

In [101]:
#Vamos a usar un groupby para crear un diccionario de los nombres y años de mandato.

dic_pres = (
    df_yr_na.groupby('president_name', observed=True)['election_year'].agg(list).to_dict()
)

print(dic_pres)
#con agg list, añade cada grupo a una listad
#con to_dict() lo convierte en un diccionario

{'Agatha Barbara': [1981], 'Bibi Ameenah Firdaus Gurib-Fakim': [2014], 'Bidhya Devi Bhandari': [2017], 'Chandrika Bandaranaike Kumaratunga': [1994, 2000, 2001, 2004], 'Corazon Aquino': [1987], 'Cristina Fernandez de Kirchner': [2007, 2015], 'Dalia Grybauskaite': [2012, 2016], 'Dilma Rousseff': [2010, 2014], 'Ellen Johnson-Sirleaf': [2005], 'George Tawlon Manneh Oppong Ousman Weah': [2017], 'Gloria Macapagal-Arroyo': [2001, 2004, 2007], 'Hilda Hein': [2015], 'Katerina Sakellaropoulou': [2019], 'Kersti Kaljulaid': [2019], 'Kolinda Grabar-Kitarović': [2015, 2016], 'Laura Chinchilla': [2010], 'Marie-Louise Coleiro Preca': [2017], 'Mary Patricia McAleese': [2002, 2007, 2011], 'Mary Therese Winifred Robinson': [1992, 1997], 'Megawati Sukarnoputri': [2004], 'Michelle Bachelet': [2005, 2009, 2013], 'Mireya Elisa Moscoso Rodríguez': [2004], 'Park Geun-hye': [2016], 'Pratibha Rao Patil': [2009], 'Tarja Kaarina Halonen': [2003, 2007, 2011], 'Tsai Ing-wen': [2016, 2020], 'Vaira Vīķe-Freiberga': [2002, 2006], 'Vigdís Finnbogadóttir': [1983, 1987, 1991, 1995], 'Violeta Barrios de Chamorro': [1990], 'Zuzana Čaputová': [2020]}

Ahora, organizamos en orden de los años de las listas internas y restamos los limites de esa lista, luego de eso, con eso hacemos el ranking.

In [102]:
for key in dic_pres:
  dic_pres[key].sort(reverse=True)
print(dic_pres)


#Ahora, tomamos el elemento 0 y el elemento ultimo (solo cuando hay mas de un elemento) (quienes tienen mas de un elemento son las que nos interesan)
#y restamos, luego de eso, añadimos al diccionario

for key in dic_pres:
  c=0
  a=0
  b=0
  if len(dic_pres[key]) > 1:
    a = int(dic_pres[key][0])
    b = int(dic_pres[key][-1])
    c = a-b
    #print(c)
    dic_pres[key].append(c)
    #print(dic_pres[key])

print(dic_pres)

{'Agatha Barbara': [1981], 'Bibi Ameenah Firdaus Gurib-Fakim': [2014], 'Bidhya Devi Bhandari': [2017], 'Chandrika Bandaranaike Kumaratunga': [2004, 2001, 2000, 1994], 'Corazon Aquino': [1987], 'Cristina Fernandez de Kirchner': [2015, 2007], 'Dalia Grybauskaite': [2016, 2012], 'Dilma Rousseff': [2014, 2010], 'Ellen Johnson-Sirleaf': [2005], 'George Tawlon Manneh Oppong Ousman Weah': [2017], 'Gloria Macapagal-Arroyo': [2007, 2004, 2001], 'Hilda Hein': [2015], 'Katerina Sakellaropoulou': [2019], 'Kersti Kaljulaid': [2019], 'Kolinda Grabar-Kitarović': [2016, 2015], 'Laura Chinchilla': [2010], 'Marie-Louise Coleiro Preca': [2017], 'Mary Patricia McAleese': [2011, 2007, 2002], 'Mary Therese Winifred Robinson': [1997, 1992], 'Megawati Sukarnoputri': [2004], 'Michelle Bachelet': [2013, 2009, 2005], 'Mireya Elisa Moscoso Rodríguez': [2004], 'Park Geun-hye': [2016], 'Pratibha Rao Patil': [2009], 'Tarja Kaarina Halonen': [2011, 2007, 2003], 'Tsai Ing-wen': [2020, 2016], 'Vaira Vīķe-Freiberga': [2006, 2002], 'Vigdís Finnbogadóttir': [1995, 1991, 1987, 1983], 'Violeta Barrios de Chamorro': [1990], 'Zuzana Čaputová': [2020]}
{'Agatha Barbara': [1981], 'Bibi Ameenah Firdaus Gurib-Fakim': [2014], 'Bidhya Devi Bhandari': [2017], 'Chandrika Bandaranaike Kumaratunga': [2004, 2001, 2000, 1994, 10], 'Corazon Aquino': [1987], 'Cristina Fernandez de Kirchner': [2015, 2007, 8], 'Dalia Grybauskaite': [2016, 2012, 4], 'Dilma Rousseff': [2014, 2010, 4], 'Ellen Johnson-Sirleaf': [2005], 'George Tawlon Manneh Oppong Ousman Weah': [2017], 'Gloria Macapagal-Arroyo': [2007, 2004, 2001, 6], 'Hilda Hein': [2015], 'Katerina Sakellaropoulou': [2019], 'Kersti Kaljulaid': [2019], 'Kolinda Grabar-Kitarović': [2016, 2015, 1], 'Laura Chinchilla': [2010], 'Marie-Louise Coleiro Preca': [2017], 'Mary Patricia McAleese': [2011, 2007, 2002, 9], 'Mary Therese Winifred Robinson': [1997, 1992, 5], 'Megawati Sukarnoputri': [2004], 'Michelle Bachelet': [2013, 2009, 2005, 8], 'Mireya Elisa Moscoso Rodríguez': [2004], 'Park Geun-hye': [2016], 'Pratibha Rao Patil': [2009], 'Tarja Kaarina Halonen': [2011, 2007, 2003, 8], 'Tsai Ing-wen': [2020, 2016, 4], 'Vaira Vīķe-Freiberga': [2006, 2002, 4], 'Vigdís Finnbogadóttir': [1995, 1991, 1987, 1983, 12], 'Violeta Barrios de Chamorro': [1990], 'Zuzana Čaputová': [2020]}

Listo. Ahora, solo resta comparar el ultimo valor de cada lista y encontrar el mayor.

In [112]:
#print(dic_pres)

mayor = -1
nombre = None
for key in dic_pres:
  if len(dic_pres[key]) > 1:
    period_value = dic_pres[key][-1]
    #print(period_value)

    if period_value > mayor:
      mayor = period_value
      nombre = key
  else:
    continue
print(f'La presidenta con más años continuos de mandato en una democracia fue "{nombre}" con {mayor} años.')

La presidenta con más años continuos de mandato en una democracia fue "Vigdís Finnbogadóttir" con 12 años.

In [ ]:
#SOLUCIÓN DE CHAT GPT

import pandas as pd

df = pd.read_csv("democracy_data.csv")

# Filtrar presidentas en democracias
df_fem_dem = df[
    (df["is_female_president"]) &
    (df["is_democracy"])
]

# Eliminar filas sin año electoral
df_fem_dem = df_fem_dem.dropna(subset=["election_year"]).copy()

# Convertir tipo
df_fem_dem["election_year"] = df_fem_dem["election_year"].astype(int)

# Agrupar por presidenta y calcular primer y último año
mandates = (
    df_fem_dem
    .groupby("president_name")["election_year"]
    .agg(["min", "max"])
)

# Duración del mandato
mandates["years"] = mandates["max"] - mandates["min"]

# Encontrar la mayor duración
winner = mandates["years"].idxmax()
max_years = mandates["years"].max()

print(f'La presidenta con más años continuos de mandato en una democracia fue "{winner}" con {max_years} años.')